### ISSUE TITLE
character and locations names

### ISSUE THREAD

**Issue by davideghz** [scottyg/forcem-ipsum#9]
Hi, I noticed in the 2022 version character and locations names are missing; do you plan to implement them again?
Thank you, Davide

**Comment by scottyg** [comment]
Sorry about that. I can add them back in this week. Ideally, I'd like to add some characters and locations from the new movies and tv series.

**Comment by scottyg** [comment]
@davideghz I have added characters and planets back into the node package and on [forcemipsum.com](https://forcemipsum.com)
